/**
 * Diff Command - Generate unified diff patch for code changes
 */

import chalk from 'chalk';
import { readFileSync } from 'fs';
import { MCPClient } from '../client.js';
import { basename, extname } from 'path';

export async function diffCommand(
    filePath: string,
    options: {
        prompt?: string;
        endpoint?: string;
        apiKey?: string;
        apply?: boolean;
    }
): Promise<void> {
    const client = new MCPClient(options.endpoint, options.apiKey);

    let fileContent: string;
    let fileName: string;
    let language: string;

    // Read file
    try {
        fileContent = readFileSync(filePath, 'utf-8');
        fileName = basename(filePath);
        language = detectLanguage(filePath);
        console.log(chalk.dim(`📖 Read file: ${fileName} (${language})\n`));
    } catch (error) {
        console.error(chalk.red(`❌ Cannot read file: ${filePath}`));
        console.error(chalk.dim(error instanceof Error ? error.message : String(error)));
        process.exit(1);
    }

    const prompt = options.prompt || 'Please suggest improvements and provide a unified diff patch.';

    console.log(chalk.dim('⏳ Requesting diff from MCP server...\n'));

    const context = client.getCurrentContext();
    // Add file info to context
    if (context.context) {
        context.context.filename = filePath;
        context.context.language = language;
    }

    // Include file content in message
    const fullMessage = `${prompt}\n\nFile: ${filePath}\nLanguage: ${language}\n\n\`\`\`${language}\n${fileContent}\n\`\`\``;

    try {
        const response = await client.send({
            mode: 'diff',
            message: fullMessage,
            ...context,
        });

        printResponse(response);

        // If --apply flag is set and patch exists
        if (options.apply && response.patch) {
            console.log(chalk.yellow('\n⚠️  Apply patch functionality not yet implemented'));
            console.log(chalk.dim('To apply manually: save patch to file.patch and run:'));
            console.log(chalk.dim('  git apply file.patch'));
            console.log(chalk.dim('  or'));
            console.log(chalk.dim('  patch -p1 < file.patch\n'));
        }
    } catch (error) {
        process.exit(1);
    }
}

/**
 * Detect programming language from file extension
 */
function detectLanguage(filePath: string): string {
    const ext = extname(filePath).toLowerCase();

    const langMap: Record<string, string> = {
        '.js': 'javascript',
        '.ts': 'typescript',
        '.jsx': 'javascript',
        '.tsx': 'typescript',
        '.py': 'python',
        '.java': 'java',
        '.c': 'c',
        '.cpp': 'cpp',
        '.go': 'go',
        '.rs': 'rust',
        '.rb': 'ruby',
        '.php': 'php',
    };

    return langMap[ext] || 'text';
}

/**
 * Print diff response with patch
 */
function printResponse(response: any): void {
    const { message, patch, model, tokens, cost } = response;

    // Print explanation message
    console.log(chalk.cyan('╔' + '═'.repeat(58) + '╗'));
    console.log(chalk.cyan('║') + chalk.bold(' MCP DIFF RESPONSE ').padEnd(58) + chalk.cyan('║'));
    console.log(chalk.cyan('╚' + '═'.repeat(58) + '╝\n'));

    console.log(chalk.white(message || 'Diff generated'));
    console.log();

    // Print patch if available
    if (patch) {
        console.log(chalk.yellow('╔' + '═'.repeat(58) + '╗'));
        console.log(chalk.yellow('║') + chalk.bold(' UNIFIED DIFF PATCH ').padEnd(58) + chalk.yellow('║'));
        console.log(chalk.yellow('╚' + '═'.repeat(58) + '╝\n'));

        // Syntax highlight diff
        printHighlightedDiff(patch);

        console.log();
        console.log(chalk.dim('💡 Tip: To apply this patch, save it to a file and run:'));
        console.log(chalk.dim('   git apply <patch-file>'));
        console.log(chalk.dim('   or'));
        console.log(chalk.dim('   patch < <patch-file>\n'));
    } else {
        console.log(chalk.yellow('⚠️  No patch generated by AI\n'));
    }

    if (model) {
        const totalTokens = tokens?.total || 0;
        const costStr = cost ? `$${cost.toFixed(4)}` : '';
        console.log(chalk.dim(`📊 Model: ${model} | Tokens: ${totalTokens} ${costStr ? `| Cost: ${costStr}` : ''}\n`));
    }
}

/**
 * Print diff with syntax highlighting
 */
function printHighlightedDiff(diff: string): void {
    const lines = diff.split('\n');

    for (const line of lines) {
        if (line.startsWith('+++') || line.startsWith('---')) {
            console.log(chalk.bold.white(line));
        } else if (line.startsWith('+')) {
            console.log(chalk.green(line));
        } else if (line.startsWith('-')) {
            console.log(chalk.red(line));
        } else if (line.startsWith('@@')) {
            console.log(chalk.cyan(line));
        } else if (line.startsWith('diff --git')) {
            console.log(chalk.yellow(line));
        } else {
            console.log(chalk.dim(line));
        }
    }
}
